site: Neos Blogs
title: Neos Blogs
description: >-
  tessing blog site for Neos Talks
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
timezone: India
repo: https://github.com/neos-20/neos-blogs # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: Umang
  bio: i see no god up here , OTHER THAN ME
  username: umgbhalla # general username
  github: umgbhalla # github username
  twitter: umgbhalla # twitter username
  email: umg.bhalla55@gmail.com # email adress

# URL settings
url: "https://neos-20.github.io/neos-blogs" # Domain Name of host. [username].github.io for github pages
baseurl: "/neos-20" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


